apiVersion: v1
kind: Service
metadata:
  name: back-end

spec:
  type: ClusterIP
  ports:
  - targetPort: 80   #  [port exposed by pod]
    port: 80         #  [port presented on service object]

  selector:          #  [comes from the metadata labels of the target pod]
    app: myapp
    type: front-end