apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    tier: front-end
spec:
  containers:
    - name: nginx-container
      image: 192.168.56.1:5000/nginx
      imagePullPolicy: IfNotPresent